<?php /** @var Magento\Framework\View\Element\Template $block */?>
<?php $status = $block->getStatus();?>
<?php if($status!= -1): ?>
<h3>Your status is <?php echo $block->getStatusFromOptionsArray($status);?></h3>
<p><?php echo $block->statusDescribe($status);
$item = $block->getAllCreditInfo();
if($item!=null):
?></p>
<?php endif;?>

<?php else: ?>
<form class="form"
      action="<?= $block->escapeUrl($block->getUrl('credit/customer/form')) ?>"
      method="post"
      enctype="multipart/form-data" >

    <fieldset class="fieldset info">
        <legend class="legend"><span><?= $block->escapeHtml(__('Credit Information')) ?></span></legend><br>


        <div class="field required">
            <label class="label">
                <span><?= $block->escapeHtml(__('First Name')) ?></span>
            </label>
            <input type="text" name="first_name">
        </div>

        <div class="field required">
            <label class="label">
                <span><?= $block->escapeHtml(__('Last Name')) ?></span>
            </label>
            <input type="text" name="last_name">
        </div>

        <div class="field required">
            <label class="label">
                <span><?= $block->escapeHtml(__('Email')) ?></span>
            </label>
            <input type="email" name="email">
        </div>

        <div class="field required">
            <label class="label">
                <span><?= $block->escapeHtml(__('Phone Number')) ?></span>
            </label>
            <input type="number" name="phone_number">
        </div>

        <div class="field required">
            <label class="label">
                <span><?= $block->escapeHtml(__('Credit limit')) ?></span>
            </label>
            <input type="number" placeholder="1 000 000" name="credit_amount">
        </div>


        <div class="field required">
            <label class="label">
                <span><?= $block->escapeHtml(__('Upload file')) ?></span>
            </label>
            <input type="hidden" name="MAX_FILE_SIZE" value="10000000" />
            <input class="file-uploader " type="file" id="file" name="file" value="">
        </div>

        <div class="actions-toolbar">
            <div class="primary">
                <button type="submit" class="action save primary" title="<?= $block->escapeHtmlAttr(__('Save')) ?>">
                    <span><?= $block->escapeHtml(__('Save')) ?></span>
                </button>
            </div>
        </div>
    </fieldset>
</form>
<?php endif; ?>
